// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuS7z6CggnyM9XlrXp9ej8ZTw7mw51TRA',
    appId: '1:276133735757:web:b759abf5ec022255261b04',
    messagingSenderId: '276133735757',
    projectId: 'orders-app-fe7a1',
    authDomain: 'orders-app-fe7a1.firebaseapp.com',
    storageBucket: 'orders-app-fe7a1.firebasestorage.app',
    measurementId: 'G-9BZSHLZN3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDG7y04uW0cPeTigzN3VNi5tqyMjkOXes',
    appId: '1:276133735757:android:2051cee9e63fa1a9261b04',
    messagingSenderId: '276133735757',
    projectId: 'orders-app-fe7a1',
    storageBucket: 'orders-app-fe7a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCplHYS8te7ZhlcNk6YhVO8uLy_bCOlG88',
    appId: '1:276133735757:ios:3dded72d0836fd7c261b04',
    messagingSenderId: '276133735757',
    projectId: 'orders-app-fe7a1',
    storageBucket: 'orders-app-fe7a1.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCplHYS8te7ZhlcNk6YhVO8uLy_bCOlG88',
    appId: '1:276133735757:ios:3dded72d0836fd7c261b04',
    messagingSenderId: '276133735757',
    projectId: 'orders-app-fe7a1',
    storageBucket: 'orders-app-fe7a1.firebasestorage.app',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuS7z6CggnyM9XlrXp9ej8ZTw7mw51TRA',
    appId: '1:276133735757:web:50af4cfe16be9eeb261b04',
    messagingSenderId: '276133735757',
    projectId: 'orders-app-fe7a1',
    authDomain: 'orders-app-fe7a1.firebaseapp.com',
    storageBucket: 'orders-app-fe7a1.firebasestorage.app',
    measurementId: 'G-DJW9RZK3SB',
  );
}
